name: python_libs_playground

channels:
    - defaults
    - conda-forge

dependencies:
    - python>=3.9  # The first line should always be python version
    - pip
    - pillow
    - ephem # high-precision astronomy computations
    - pytz
    - pip:
          - wordcloud
          - pypdf2 # wordcloud dependency
          - jieba # wordcloud dependency
          - tzwhere # latitude, longitude to timezone
          - paddlepaddle  # check which python version it uses
          - paddleocr # install after paddlepaddle

